### ISSUE TITLE
Something is broken in the latest master. 

### ISSUE THREAD

**Issue by iandobbie** [python-microscope/microscope#176]
I have a current master copy of microscope and am trying to start a deviceserver. My config file is:

#!/usr/bin/env python

from microscope.devices import device
import microscope.testsuite.devices as testdevices

DEVICES = [
    device(testdevices.TestCamera, '127.0.0.1', 8000,),
]

but starting deviceserver config.py

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/deviceserver", line 33, in <module>
    sys.exit(load_entry_point('microscope', 'console_scripts', 'deviceserver')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/deviceserver", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'microscope.deviceserver' has no attribute '__main__'

However deviceserever does have a function __main__

**Comment by carandraug** [comment]
Me and Ian fixed this now. It was a case of mixed old installations with different permissions. This was fixed by removing all previous installations (manually checking on the python library directory for microscope), and the `microscope.egg-info` directory on the microscope repository). and then install again.
