### ISSUE TITLE
Add an option for log file location to device server.

### ISSUE THREAD

**Issue by iandobbie** [python-microscope/microscope#267]
The device server accepts a logging_level option I think we should add a logging_dir option as well. The root of this need is the cockpit-distribution code for the simulation with a large image used to simulate a microscope. On a Mac the newer versions of MacOS (sorry don't know how new but happens with 12.6.2) will not open relative paths with sandboxed apps, such as those built with pyinstaller. 

The device server currently open log files as simply 

log_handler = RotatingFileHandler(
            "%s_%s_%s.log" % (cls_name, host, port)
        )

Which is just a relative path to the current working directory. In the mac packaged app this kills the device_server breaking the simulation mode application.  More details in the thread at:

https://github.com/carandraug/cockpit-distribution/issues/2

**Comment by iandobbie** [comment]
I have a implementation in https://github.com/iandobbie/microscope/tree/log_path which adds a logging_path option to the device server.

**Comment by iandobbie** [comment]
I intend to pull this patch as it fixes the cockpit-distribution problem and may enable issue #268 to be done with no or minimal extra effort, by using  logging_path config to define a remote destination for the logs.

**Comment by carandraug** [comment]
Are you just prefixing the filename with `logpath` to support the case of including a file prefix in `logging_path`? If so, I think this can be confusing because someone trying to just specify a directory without the trailing `/` will fail. If this was not by purpose, can we renamed the option `--logs-dir` or `--logging-dir` ?

Also, because `DeviceServerOptions.logging_path` is a required attributed, there's no need to check for its value.

Or, I was never a fan of writing the log files by default to the current working directory. This is never what I want and even makes testing the device server trickier. Could this option also define whether log files should be created at all (or if messages to stdout is enough)?

**Comment by iandobbie** [comment]
Both good suggestions. I'll have a look at the patch and edit it.

**Comment by carandraug** [comment]
Done. Closing as fixed.
